# Example labeler configuration for Frappe Theme
# Map file patterns to PR labels. Adjust as needed for your repo structure.

enhancement:
  - paths:
      - "apps/frappe_theme/frontend/**"
      - "apps/frappe_theme/backend/**"
docs:
  - paths:
      - "**/*.md"
test:
  - paths:
      - "**/test_*.py"
chore:
  - paths:
      - "scripts/**"
style:
  - paths:
      - "**/*.css"
      - "**/*.scss"
      - "**/*.less"
release:
  - paths:
      - "bench-v*/patches.txt"
